[package]
name = "libuv-subprocess-windows"
version = "0.1.0"
edition = "2024"

[dependencies]
futures-channel = "0.3.31"
libc = "0.2.172"

[target.x86_64-pc-windows-gnu.dependencies]
windows-sys = { version = "0.59.0", features = [
  "Win32_Security",
  "Win32_System_JobObjects",
  "Win32_System_Diagnostics_Debug",
  "Win32_Globalization",
  "Win32_System_Threading",
  "Win32_Storage_FileSystem",
  "Win32_System_Environment",
  "Win32_Foundation",
  "Win32_System_Kernel",
  "Win32_System_Memory",
  "Win32_System_ProcessStatus",
  "Win32_System_Registry",
  "Win32_UI_Shell",
  "Win32_System_Com",
  "Win32_System_WindowsProgramming",
  "Win32_UI_WindowsAndMessaging",
  "Win32_System_Pipes",
  "Win32_System_Console",
] }
[target.x86_64-pc-windows-msvc.dependencies]
windows-sys = { version = "0.59.0", features = [
  "Win32_Security",
  "Win32_System_JobObjects",
  "Win32_System_Diagnostics_Debug",
  "Win32_Globalization",
  "Win32_System_Threading",
  "Win32_Storage_FileSystem",
  "Win32_System_Environment",
  "Win32_Foundation",
  "Win32_System_Kernel",
  "Win32_System_Memory",
  "Win32_System_ProcessStatus",
  "Win32_System_Registry",
  "Win32_UI_Shell",
  "Win32_System_Com",
  "Win32_System_WindowsProgramming",
  "Win32_UI_WindowsAndMessaging",
  "Win32_System_Pipes",
  "Win32_System_Console",
] }

[dev-dependencies]
pretty_assertions = "1.4.1"
